// Generated by CoffeeScript 1.3.3
(function() {

  window.idleNotificationInitialize = function() {
    var idleTextElement, urlParams;
    urlParams = {};
    (function() {
      var a, d, e, q, r, _results;
      e = null;
      a = /\+/g;
      r = /([^&=]+)=?([^&]*)/g;
      d = function(s) {
        return decodeURIComponent(s.replace(a, ' '));
      };
      q = window.location.search.substring(1);
      _results = [];
      while (e = r.exec(q)) {
        _results.push(urlParams[d(e[1])] = d(e[2]));
      }
      return _results;
    })();
    window.idleNotificationData = {
      idleSeconds: parseInt(urlParams.idleSeconds, 10),
      timeEntryID: parseInt(urlParams.timeEntryID, 10),
      idleAt: parseInt(urlParams.idleAt, 10),
      idleText: urlParams.idleText
    };
    idleTextElement = document.getElementById('idleText');
    return idleTextElement.innerHTML = 'You have been idle for ' + window.idleNotificationData.idleText + '..';
  };

  window.idleNotificationCommand = function(command) {
    var backgroundPage;
    try {
      if (chrome && chrome.extension && chrome.extension.getBackgroundPage) {
        backgroundPage = chrome.extension.getBackgroundPage();
        if (backgroundPage) {
          return backgroundPage.toggl.app.trigger(command, window.idleNotificationData);
        }
      }
    } catch (e) {

    } finally {
      window.close();
    }
  };

  $(function() {
    window.idleNotificationInitialize();
    $('.idle-keep').click(function() {
      return window.close();
    });
    $('.idle-drop').click(function() {
      return window.idleNotificationCommand('idleDrop');
    });
    return $('.idle-split').click(function() {
      return window.idleNotificationCommand('idleSplit');
    });
  });

}).call(this);
