var Hoptoad={VERSION:"0.1.0",NOTICE_XML:'<?xml version="1.0" encoding="UTF-8"?><notice version="2.0"><api-key></api-key><notifier><name>airbrake_js</name><version>0.1.0</version><url>http://airbrake.io</url></notifier><error><class>EXCEPTION_CLASS</class><message>EXCEPTION_MESSAGE</message><backtrace>BACKTRACE_LINES</backtrace></error><request><url>REQUEST_URL</url><component>REQUEST_COMPONENT</component><action>REQUEST_ACTION</action></request><server-environment><project-root>PROJECT_ROOT</project-root><environment-name>production</environment-name></server-environment></notice>',
ROOT:window.location.protocol+"//"+window.location.host,BACKTRACE_MATCHER:/^(.*)\@(.*)\:(\d+)$/,backtrace_filters:[/notifier\.js/],notify:function(a){var a=escape(Hoptoad.generateXML(a)),a="https://"+(Hoptoad.host||"airbrake.io")+"/notifier_api/v2/notices?data="+a,b=document.createElement("iframe");b.style.width="1px";b.style.height="1px";b.style.display="none";b.src=a;document.getElementsByTagName("head")[0].appendChild(b)},setEnvironment:function(a){Hoptoad.NOTICE_XML=Hoptoad.NOTICE_XML.replace(/<environment-name>.*<\/environment-name>/,
"<environment-name>"+a+"</environment-name>")},setHost:function(a){Hoptoad.host=a},setKey:function(a){Hoptoad.NOTICE_XML=Hoptoad.NOTICE_XML.replace(/<api-key>.*<\/api-key>/,"<api-key>"+a+"</api-key>")},setErrorDefaults:function(a){Hoptoad.errorDefaults=a},generateXML:function(a){var a=Hoptoad.mergeDefault(Hoptoad.errorDefaults,a),b=Hoptoad.NOTICE_XML,c=Hoptoad.escapeText((a.url||"")+(location.hash||"")||""),d=Hoptoad.escapeText(a.component||""),e=Hoptoad.escapeText(a.action||""),g=Hoptoad.escapeText(a.type||
"Error"),f=Hoptoad.escapeText(a.message||"Unknown error."),l=Hoptoad.generateBacktrace(a);if(""==Hoptoad.trim(c)&&""==Hoptoad.trim(d))b=b.replace(/<request>.*<\/request>/,"");else{var h;h=a["cgi-data"]||{};h.HTTP_USER_AGENT=navigator.userAgent;h="<cgi-data>"+Hoptoad.generateVariables(h);h+="</cgi-data>";for(var j=["params","session"],i=0;2>i;i++){var k=j[i];a[k]&&(h+="<"+k+">",h+=Hoptoad.generateVariables(a[k]),h+="</"+k+">")}b=b.replace("</request>",h+"</request>").replace("REQUEST_URL",c).replace("REQUEST_ACTION",
e).replace("REQUEST_COMPONENT",d)}try{window.toggl&&(window.toggl.app&&window.toggl.app.currentUser)&&l.push('<line method="'+window.toggl.app.currentUser.id.toString()+'" file="userId" number="0"/>'),window.toggl&&window.toggl.TogglMobileVersion&&l.push('<line method="'+window.toggl.TogglMobileVersion.toString()+'" file="togglVersion" number="0"/>'),window.toggl&&(window.toggl.app&&window.toggl.app.createdWith)&&l.push('<line method="'+window.toggl.app.createdWith.toString()+'" file="createdWith" number="0"/>'),
navigator&&navigator.userAgent&&l.push('<line method="'+navigator.userAgent.toString()+'" file="userAgent" number="0"/>')}catch(m){}return b.replace("PROJECT_ROOT",Hoptoad.ROOT).replace("EXCEPTION_CLASS",g).replace("EXCEPTION_MESSAGE",f).replace("BACKTRACE_LINES",l.join(""))},generateBacktrace:function(a){a=a||{};if("string"!=typeof a.stack)try{0()}catch(b){a.stack=b.stack}for(var c=[],a=Hoptoad.getStackTrace(a),d=0,e=a.length;d<e;d++){var g=a[d],f=g.match(Hoptoad.BACKTRACE_MATCHER);f&&Hoptoad.validBacktraceLine(g)&&
(g=f[2].replace(Hoptoad.ROOT,"[PROJECT_ROOT]"),0==d&&f[2].match(document.location.href)&&c.push('<line method="" file="internal: " number=""/>'),c.push('<line method="'+Hoptoad.escapeText(f[1])+'" file="'+Hoptoad.escapeText(g)+'" number="'+f[3]+'" />'))}return c},getStackTrace:function(a){for(var a=printStackTrace({e:a,guess:!1}),b=0,c=a.length;b<c;b++)a[b].match(/\:\d+$/)||(-1==a[b].indexOf("@")&&(a[b]+="@unsupported.js"),a[b]+=":0");return a},validBacktraceLine:function(a){for(var b=0;b<Hoptoad.backtrace_filters.length;b++)if(a.match(Hoptoad.backtrace_filters[b]))return!1;
return!0},generateVariables:function(a){var b,c="";for(b in a)c+='<var key="'+Hoptoad.escapeText(b)+'">'+Hoptoad.escapeText(a[b])+"</var>";return c},escapeText:function(a){return a.replace(/&/g,"&#38;").replace(/</g,"&#60;").replace(/>/g,"&#62;").replace(/'/g,"&#39;").replace(/"/g,"&#34;")},trim:function(a){return a.toString().replace(/^\s+/,"").replace(/\s+$/,"")},mergeDefault:function(a,b){var c={},d;for(d in b)c[d]=b[d];for(d in a)c.hasOwnProperty(d)||(c[d]=a[d]);return c}};
function printStackTrace(a){var a=a||{guess:!0},b=a.e||null,a=!!a.guess,c=new printStackTrace.implementation,b=c.run(b);return a?c.guessFunctions(b):b}printStackTrace.implementation=function(){};
printStackTrace.implementation.prototype={run:function(a){var a=a||this.createException(),b=this.mode(a);return"other"===b?this.other(arguments.callee):this[b](a)},createException:function(){try{return this.undef(),null}catch(a){return a}},mode:function(a){return a.arguments&&a.stack?this._mode="chrome":"undefined"!==typeof window&&window.opera?this._mode=a.stacktrace?"opera10":"opera":a.stack?this._mode="firefox":this._mode="other"},instrumentFunction:function(a,b,c){a=a||window;a["_old"+b]=a[b];
a[b]=function(){c.call(this,printStackTrace());return a["_old"+b].apply(this,arguments)};a[b]._instrumented=!0},deinstrumentFunction:function(a,b){a[b].constructor===Function&&a[b]._instrumented&&a["_old"+b].constructor===Function&&(a[b]=a["_old"+b])},chrome:function(a){return a.stack.replace(/^[^\(]+?[\n$]/gm,"").replace(/^\s+at\s+/gm,"").replace(/^Object.<anonymous>\s*\(/gm,"{anonymous}()@").split("\n")},firefox:function(a){return a.stack.replace(/(?:\n@:0)?\s+$/m,"").replace(/^\(/gm,"{anonymous}(").split("\n")},
opera10:function(a){var a=a.stacktrace.split("\n"),b=/.*line (\d+), column (\d+) in ((<anonymous function\:?\s*(\S+))|([^\(]+)\([^\)]*\))(?: in )?(.*)\s*$/i,c,d,e;c=2;d=0;for(e=a.length;c<e-2;c++)if(b.test(a[c])){var g=RegExp.$6+":"+RegExp.$1+":"+RegExp.$2,f=RegExp.$3,f=f.replace(/<anonymous function\:?\s?(\S+)?>/g,"{anonymous}");a[d++]=f+"@"+g}a.splice(d,a.length-d);return a},opera:function(a){var a=a.message.split("\n"),b=/Line\s+(\d+).*script\s+(http\S+)(?:.*in\s+function\s+(\S+))?/i,c,d,e;c=4;
d=0;for(e=a.length;c<e;c+=2)b.test(a[c])&&(a[d++]=(RegExp.$3?RegExp.$3+"()@"+RegExp.$2+RegExp.$1:"{anonymous}()@"+RegExp.$2+":"+RegExp.$1)+" -- "+a[c+1].replace(/^\s+/,""));a.splice(d,a.length-d);return a},other:function(a){for(var b=/function\s*([\w\-$]+)?\s*\(/i,c=[],d,e;a&&10>c.length;)d=b.test(a.toString())?RegExp.$1||"{anonymous}":"{anonymous}",e=Array.prototype.slice.call(a.arguments||[]),c[c.length]=d+"("+this.stringifyArguments(e)+")",a=a.caller;return c},stringifyArguments:function(a){for(var b=
0;b<a.length;++b){var c=a[b];void 0===c?a[b]="undefined":null===c?a[b]="null":c.constructor&&(c.constructor===Array?a[b]=3>c.length?"["+this.stringifyArguments(c)+"]":"["+this.stringifyArguments(Array.prototype.slice.call(c,0,1))+"..."+this.stringifyArguments(Array.prototype.slice.call(c,-1))+"]":c.constructor===Object?a[b]="#object":c.constructor===Function?a[b]="#function":c.constructor===String&&(a[b]='"'+c+'"'))}return a.join(",")},sourceCache:{},ajax:function(a){var b=this.createXMLHTTPObject();
if(b)return b.open("GET",a,!1),b.setRequestHeader("User-Agent","XMLHTTP/1.0"),b.send(""),b.responseText},createXMLHTTPObject:function(){for(var a,b=[function(){return new XMLHttpRequest},function(){return new ActiveXObject("Msxml2.XMLHTTP")},function(){return new ActiveXObject("Msxml3.XMLHTTP")},function(){return new ActiveXObject("Microsoft.XMLHTTP")}],c=0;c<b.length;c++)try{return a=b[c](),this.createXMLHTTPObject=b[c],a}catch(d){}},isSameDomain:function(a){return-1!==a.indexOf(location.hostname)},
getSource:function(a){a in this.sourceCache||(this.sourceCache[a]=this.ajax(a).split("\n"));return this.sourceCache[a]},guessFunctions:function(a){for(var b=0;b<a.length;++b){var c=a[b],d=/\{anonymous\}\(.*\)@(\w+:\/\/([\-\w\.]+)+(:\d+)?[^:]+):(\d+):?(\d+)?/.exec(c);if(d){var e=d[1],d=d[4];e&&this.isSameDomain(e)&&d&&(e=this.guessFunctionName(e,d),a[b]=c.replace("{anonymous}",e))}}return a},guessFunctionName:function(a,b){var c;try{c=this.guessFunctionNameFromLines(b,this.getSource(a))}catch(d){c=
"getSource failed with url: "+a+", exception: "+d.toString()}return c},guessFunctionNameFromLines:function(a,b){for(var c=/function ([^(]*)\(([^)]*)\)/,d=/['"]?([0-9A-Za-z_]+)['"]?\s*[:=]\s*(function|eval|new Function)/,e="",g=0;10>g;++g)if(e=b[a-g]+e,void 0!==e){var f=d.exec(e);if(f&&f[1]||(f=c.exec(e))&&f[1])return f[1]}return"(?)"}};
window.onerror=function(a,b,c){window.chrome&&window.chrome.togglDesktop&&alert("An error has occurred ("+a+"). We have been notified, please restart your application");if(/atomicFindClose/.test(a)||/NS_ERROR_XPC_NOT_ENOUGH_ARGS/.test(a)||/_bindRoutes/.test(a))return!0;setTimeout(function(){Hoptoad.notify({message:a,stack:"()@"+b+":"+c})},100);return!0};
